# Generated by Django 5.1.7 on 2025-03-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
