# Generated by Django 5.1.7 on 2025-03-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_playlist_options_alter_playlistsong_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlists',
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='playlist_songs',
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
        migrations.AlterModelTable(
            name='user',
            table='taikhoan',
        ),
    ]
