# Generated by Django 5.2 on 2025-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_ispremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='premium',
            field=models.IntegerField(default=0),
        ),
    ]
